version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: aktien-db
      POSTGRES_USER: huzaifa
      POSTGRES_PASSWORD: Django.123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
