# Generated by Django 4.2.14 on 2024-12-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="alert",
            unique_together={("stock", "alert_name", "alert_datetime")},
        ),
    ]
