# Generated by Django 4.2.14 on 2024-12-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
        ("alerts", "0002_alter_alert_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="alert",
            unique_together={("stock", "alert_name")},
        ),
    ]
