# Generated by Django 4.2.14 on 2024-11-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "ticker",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("exchange", models.CharField(max_length=20)),
                ("sector", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_cap", models.DecimalField(decimal_places=2, max_digits=15)),
                ("avg_volume", models.BigIntegerField()),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("current_volume", models.BigIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="stocks.stock",
                    ),
                ),
            ],
        ),
    ]
